In [1]:
#imports
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB


In [2]:
df = pd.read_csv('bug_data.csv')
df.head()
df.dropna(inplace=True)

In [3]:
from sklearn.utils import resample
normal =df[df.severity=='normal']
major =df[df.severity=='major']
minor =df[df.severity=='minor']
blocker =df[df.severity=='blocker']
trivial =df[df.severity=='trivial']
critical =df[df.severity=='critical']
enhancement =df[df.severity=='enhancement']

def resample_df(df):
    return resample(df,replace=True,n_samples=5000)

normal =resample_df(normal)
major =resample_df(major)
minor =resample_df(minor)
blocker =resample_df(blocker)
trivial =resample_df(trivial)
critical =resample_df(critical)
enhancement =resample_df(enhancement)

df = pd.concat([major,critical,minor,blocker])


df.severity.value_counts()


major       5000
critical    5000
minor       5000
blocker     5000
Name: severity, dtype: int64

In [4]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix


# Preprocess text
def preprocess_text(text):
    # Add your preprocessing steps here
    return text

df['description'] = df['description'].apply(preprocess_text)

# Vectorize text
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['description'])
y = df['severity']

# Split data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train MLP model
mlp = MLPClassifier(hidden_layer_sizes=(50,), max_iter=1000)
%time mlp.fit(X_train, y_train)

# Evaluate model
y_pred = mlp.predict(X_test)
print('Classification Report:\n', classification_report(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))


CPU times: user 14min 22s, sys: 10min 10s, total: 24min 33s
Wall time: 10min 2s
Classification Report:
               precision    recall  f1-score   support

     blocker       0.67      0.82      0.74       977
    critical       0.65      0.58      0.61      1024
       major       0.45      0.43      0.44       995
       minor       0.60      0.56      0.58      1004

    accuracy                           0.60      4000
   macro avg       0.59      0.60      0.59      4000
weighted avg       0.59      0.60      0.59      4000

Confusion Matrix:
 [[798  45  86  48]
 [147 593 193  91]
 [158 168 430 239]
 [ 90 106 247 561]]
